[General]
SyntaxVersion=1
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=b4d8d6d0-fddd-41fb-a8e5-6bdd25e0e81e
Description=鼠标右键点我
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[Relative]
SetupOCXFile=
[Comment]
Content=.
【功能说明】.
这个脚本很无聊 ：）.
只是希望告诉大家怎么使用脚本分类.
.
鼠标右键点脚本可以将脚本移到别的分类.
.
.
.
.

[Script]
MessageBox "这个脚本很无聊 ：）  只是希望告诉大家怎么使用脚本分类。鼠标右键点脚本可以将脚本移到别的分类"
